services:
  openhab:
    image: "openhab/openhab:latest"
    container_name: openhab
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./addons:/openhab/addons"
      - "./conf:/openhab/conf"
      - "./userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Kyiv"
      OPENHAB_HTTP_PORT: "8080"